name: Deploy Test File

on:
  workflow_dispatch:
  push:
    branches:
      - "prod"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload test file
        uses: actions/upload-pages-artifact@v2
        with:
          path: deploytest

      - name: Dummy step to fix upload-artifact bug
        uses: actions/upload-artifact@v3
        with:
          name: dummy
          path: /dev/null

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
